name: Assign Reviewers

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is not a draft
        id: check_draft
        run: echo "IsDraft=${{ github.event.pull_request.draft }}" >> $GITHUB_ENV

      - name: Debug IsDraft value
        run: echo "IsDraft is ${{ steps.check_draft.outputs.IsDraft }}"

      - name: Assign reviewers if not a draft
        if: steps.check_draft.outputs.IsDraft == 'false'
        run: |
          # Use the auto-assign-action to add reviewers here
          # Add your commands to assign reviewers to the PR
          echo "Assigning reviewers..."
