name: Code Quality Check
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && !startsWith(github.base_ref,
      'release/') && github.event.head_commit.message != 'chore: Auto-run Prettier on files in PR'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check Last Commit Message
        run: echo $(git log -1 --pretty=%s)
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: "shell"
          filters: |
            client:
              - '{client/src,client/project_utils,client/puppeteer,client/tests}/**/*.{js,ts,tsx,json}'
              - 'client/*.{js,ts,json}'
              - '.github/**/*.yml'
      - name: Save Branch Name to GitHub Environment Variable
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install
      - name: Check Prettier Formatting
        id: prettier-check
        if: ${{ steps.filter.outputs.client == 'true' || steps.filter.outputs.parent == 'true' }}
        run: |
          npx prettier --check ${{ steps.filter.outputs.client_files }} --ignore-path="{../yarn.lock,../package.json}"
        continue-on-error: true
      - name: Auto-format Code and Commit Prettier Changes
        if: steps.prettier-check.outcome == 'failure'
        run: |
          git fetch --unshallow
          git checkout ${{ env.BRANCH_NAME }}
          npx prettier --write ${{ steps.filter.outputs.client_files }} ${{ steps.filter.outputs.parent_files }} --ignore-path="{../yarn.lock,../package.json}"
          git config --global user.email "aaa@gmail.com"
          git config --global user.name "aa Dev Bot"
          git add -A
          git reset yarn.lock
          git commit -m "chore: Auto-run Prettier on files in PR" --no-verify
          git push origin ${{ env.BRANCH_NAME }}
  eslint:
    if: always() && github.event_name == 'pull_request' && (github.base_ref ==
      'nextjs' || github.base_ref == 'nextjs-prod'
      ||  startsWith(github.base_ref, 'release/'))
    needs: prettier
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: |
          yarn install
      - name: Run eslint
        run: yarn lint
        env:
          CI: true
